"""add unique constraint uq_repo_stats_repo_hour

Revision ID: 86af5456b080
Revises: fec917d3faaf
Create Date: 2026-09-15 19:49:37.513016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '86af5456b080'
down_revision: Union[str, Sequence[str], None] = 'fec917d3faaf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_repo_stats_repo_hour', 'repo_stats', ['repo_id', 'stat_hour'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_repo_stats_repo_hour', 'repo_stats', type_='unique')
    # ### end Alembic commands ###
