"""add stats_aggregation_state table

Revision ID: 9478c3e10b0f
Revises: 86af5456b080
Create Date: 2026-09-15 20:30:37.259497

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9478c3e10b0f'
down_revision: Union[str, Sequence[str], None] = '86af5456b080'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """建表 + 重算预聚合数据（成功口径变更）。"""
    op.create_table('stats_aggregation_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('aggregated_until', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # 【口径变更强制重算 —— 人工补充，autogenerate 检测不到】
    # 「成功调用」判定由阶段 1 的 "< 400" 统一为 "2xx"（与 analytics/dashboard 既有口径一致）。
    # 历史 repo_stats 行仍是旧口径（3xx 被计为成功）→ 必须清空重算，
    # 否则 analytics 读切换后"今日成功数"会与实时查询不一致（就是回归）。
    #
    # 清空是安全的：新表尚无水位行 → get_watermark() 返回 None →
    # 读侧自动回落实时查询（数值始终正确）；后台聚合任务随后从最早日志
    # 连续重新聚合（幂等 upsert），追平后自动切回预聚合路径。
    op.execute("DELETE FROM repo_stats")


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('stats_aggregation_state')
    # ### end Alembic commands ###
