"""baseline: current schema (sync from models 2026-09-15)

Revision ID: fec917d3faaf
Revises: 
Create Date: 2026-09-15 19:10:59.238996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fec917d3faaf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('adapter_instances',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('adapter_id', sa.UUID(), nullable=False),
    sa.Column('instance_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('health_status', sa.String(length=20), nullable=True),
    sa.Column('last_health_check', sa.DateTime(timezone=True), nullable=True),
    sa.Column('health_check_interval', sa.Integer(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('failed_calls', sa.Integer(), nullable=True),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapter_instances_repo_id'), 'adapter_instances', ['repo_id'], unique=False)
    op.create_table('adapters',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('adapter_type', sa.String(length=50), nullable=False),
    sa.Column('version', sa.String(length=20), nullable=False),
    sa.Column('config_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('default_config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('capabilities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('total_repos', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_adapters_adapter_type'), 'adapters', ['adapter_type'], unique=False)
    op.create_index(op.f('ix_adapters_status'), 'adapters', ['status'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('old_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_audit_action_time', 'audit_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_audit_resource_time', 'audit_logs', ['resource_type', 'created_at'], unique=False)
    op.create_index('idx_audit_user_time', 'audit_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_username'), 'audit_logs', ['username'], unique=False)
    op.create_table('notification_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('email_enabled', sa.Boolean(), nullable=True),
    sa.Column('in_app_enabled', sa.Boolean(), nullable=True),
    sa.Column('push_enabled', sa.Boolean(), nullable=True),
    sa.Column('preferences', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('notification_type', sa.String(length=30), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('extra_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.String(length=20), nullable=False),
    sa.Column('expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('platform_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='支付渠道'),
    sa.Column('account_type', sa.String(length=20), nullable=False, comment='账户类型'),
    sa.Column('account_no', sa.String(length=100), nullable=True, comment='第三方账户号'),
    sa.Column('account_name', sa.String(length=100), nullable=True, comment='账户名称'),
    sa.Column('balance', sa.DECIMAL(precision=20, scale=2), nullable=True, comment='账户余额'),
    sa.Column('currency', sa.String(length=10), nullable=True, comment='币种'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='状态: active/inactive'),
    sa.Column('remark', sa.Text(), nullable=True, comment='备注'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_platform_accounts_channel'), 'platform_accounts', ['channel'], unique=False)
    op.create_table('quotas',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_id', sa.UUID(), nullable=True),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('quota_type', sa.String(length=20), nullable=False),
    sa.Column('quota_limit', sa.BigInteger(), nullable=False),
    sa.Column('quota_used', sa.BigInteger(), nullable=True),
    sa.Column('quota_remaining', sa.BigInteger(), nullable=True),
    sa.Column('reset_type', sa.String(length=20), nullable=False),
    sa.Column('reset_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quotas_user_id'), 'quotas', ['user_id'], unique=False)
    op.create_table('recharge_packages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('original_amount', sa.String(length=20), nullable=False),
    sa.Column('price', sa.String(length=20), nullable=False),
    sa.Column('discount', sa.String(length=10), nullable=True),
    sa.Column('min_amount', sa.String(length=20), nullable=True),
    sa.Column('max_amount', sa.String(length=20), nullable=True),
    sa.Column('bonus_amount', sa.String(length=20), nullable=True),
    sa.Column('bonus_ratio', sa.String(length=10), nullable=True),
    sa.Column('included_calls', sa.BigInteger(), nullable=True),
    sa.Column('included_tokens', sa.BigInteger(), nullable=True),
    sa.Column('validity_days', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.String(length=10), nullable=True),
    sa.Column('is_featured', sa.String(length=10), nullable=True),
    sa.Column('sort_order', sa.BigInteger(), nullable=True),
    sa.Column('is_custom', sa.String(length=10), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reconciliation_disputes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reconciliation_id', sa.UUID(), nullable=True, comment='对账记录ID'),
    sa.Column('dispute_type', sa.String(length=20), nullable=False, comment='差异类型'),
    sa.Column('local_order_no', sa.String(length=100), nullable=True, comment='本地订单号'),
    sa.Column('channel_trade_no', sa.String(length=100), nullable=True, comment='第三方交易号'),
    sa.Column('local_amount', sa.DECIMAL(precision=20, scale=2), nullable=True, comment='本地金额'),
    sa.Column('channel_amount', sa.DECIMAL(precision=20, scale=2), nullable=True, comment='第三方金额'),
    sa.Column('diff_amount', sa.DECIMAL(precision=20, scale=2), nullable=True, comment='差异金额'),
    sa.Column('reason', sa.String(length=500), nullable=True, comment='差异原因'),
    sa.Column('handle_status', sa.String(length=20), nullable=True, comment='处理状态'),
    sa.Column('handle_remark', sa.Text(), nullable=True, comment='处理备注'),
    sa.Column('handler_id', sa.UUID(), nullable=True, comment='处理人ID'),
    sa.Column('handled_at', sa.DateTime(timezone=True), nullable=True, comment='处理时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_disputes_reconciliation_id'), 'reconciliation_disputes', ['reconciliation_id'], unique=False)
    op.create_table('reconciliation_records',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('reconcile_date', sa.DateTime(timezone=True), nullable=False, comment='对账日期'),
    sa.Column('channel', sa.String(length=20), nullable=False, comment='支付渠道'),
    sa.Column('platform_trade_count', sa.String(length=20), nullable=True, comment='本地交易笔数'),
    sa.Column('platform_trade_amount', sa.DECIMAL(precision=20, scale=2), nullable=True, comment='本地交易金额'),
    sa.Column('channel_trade_count', sa.String(length=20), nullable=True, comment='第三方交易笔数'),
    sa.Column('channel_trade_amount', sa.DECIMAL(precision=20, scale=2), nullable=True, comment='第三方交易金额'),
    sa.Column('match_count', sa.String(length=20), nullable=True, comment='匹配笔数'),
    sa.Column('match_amount', sa.DECIMAL(precision=20, scale=2), nullable=True, comment='匹配金额'),
    sa.Column('long_count', sa.String(length=20), nullable=True, comment='长款笔数'),
    sa.Column('long_amount', sa.DECIMAL(precision=20, scale=2), nullable=True, comment='长款金额'),
    sa.Column('short_count', sa.String(length=20), nullable=True, comment='短款笔数'),
    sa.Column('short_amount', sa.DECIMAL(precision=20, scale=2), nullable=True, comment='短款金额'),
    sa.Column('amount_diff_count', sa.String(length=20), nullable=True, comment='金额不一致笔数'),
    sa.Column('amount_diff_total', sa.DECIMAL(precision=20, scale=2), nullable=True, comment='金额差异总额'),
    sa.Column('status', sa.String(length=20), nullable=True, comment='对账状态'),
    sa.Column('bill_file_path', sa.String(length=500), nullable=True, comment='账单文件路径'),
    sa.Column('bill_content', sa.Text(), nullable=True, comment='账单文件内容'),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True, comment='完成时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reconciliation_records_channel'), 'reconciliation_records', ['channel'], unique=False)
    op.create_index(op.f('ix_reconciliation_records_reconcile_date'), 'reconciliation_records', ['reconcile_date'], unique=False)
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('display_name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('priority', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_roles_name'), 'roles', ['name'], unique=True)
    op.create_table('system_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('is_encrypted', sa.Boolean(), nullable=True),
    sa.Column('label', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('is_visible', sa.Boolean(), nullable=True),
    sa.Column('is_editable', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_by', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_system_configs_category'), 'system_configs', ['category'], unique=False)
    op.create_index(op.f('ix_system_configs_key'), 'system_configs', ['key'], unique=False)
    op.create_table('user_operation_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('username', sa.String(length=100), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('action_name', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('page', sa.String(length=255), nullable=True),
    sa.Column('page_name', sa.String(length=200), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('url_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('endpoint', sa.String(length=500), nullable=True),
    sa.Column('request_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_status', sa.String(length=20), nullable=True),
    sa.Column('old_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_values', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('device_type', sa.String(length=50), nullable=True),
    sa.Column('browser', sa.String(length=100), nullable=True),
    sa.Column('os', sa.String(length=100), nullable=True),
    sa.Column('success', sa.Boolean(), nullable=True),
    sa.Column('error_code', sa.String(length=50), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.String(length=20), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_user_op_action_time', 'user_operation_logs', ['action', 'created_at'], unique=False)
    op.create_index('idx_user_op_category_time', 'user_operation_logs', ['category', 'created_at'], unique=False)
    op.create_index('idx_user_op_session_time', 'user_operation_logs', ['session_id', 'created_at'], unique=False)
    op.create_index('idx_user_op_user_time', 'user_operation_logs', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_user_operation_logs_action'), 'user_operation_logs', ['action'], unique=False)
    op.create_index(op.f('ix_user_operation_logs_category'), 'user_operation_logs', ['category'], unique=False)
    op.create_index(op.f('ix_user_operation_logs_created_at'), 'user_operation_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_user_operation_logs_email'), 'user_operation_logs', ['email'], unique=False)
    op.create_index(op.f('ix_user_operation_logs_session_id'), 'user_operation_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_user_operation_logs_user_id'), 'user_operation_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_user_operation_logs_username'), 'user_operation_logs', ['username'], unique=False)
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('nickname', sa.String(length=100), nullable=True),
    sa.Column('avatar_url', sa.String(length=500), nullable=True),
    sa.Column('real_name', sa.String(length=100), nullable=True),
    sa.Column('company', sa.String(length=200), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('contact_email', sa.String(length=255), nullable=True),
    sa.Column('contact_phone', sa.String(length=20), nullable=True),
    sa.Column('billing_type', sa.String(length=20), nullable=True),
    sa.Column('credit_limit', sa.String(length=20), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=True),
    sa.Column('login_notify', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_profiles_user_id'), 'user_profiles', ['user_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('user_type', sa.String(length=20), nullable=False),
    sa.Column('user_status', sa.String(length=20), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('permissions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('oauth_provider', sa.String(length=50), nullable=True),
    sa.Column('oauth_id', sa.String(length=255), nullable=True),
    sa.Column('email_verified', sa.Boolean(), nullable=True),
    sa.Column('phone_verified', sa.Boolean(), nullable=True),
    sa.Column('vip_level', sa.Integer(), nullable=True),
    sa.Column('vip_expire_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('trial_claimed', sa.Boolean(), nullable=True),
    sa.Column('trial_amount_claimed', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_ip', sa.String(length=50), nullable=True),
    sa.Column('extra', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('account_type', sa.String(length=20), nullable=False),
    sa.Column('balance', sa.String(length=20), nullable=True),
    sa.Column('frozen_balance', sa.String(length=20), nullable=True),
    sa.Column('total_recharge', sa.String(length=20), nullable=True),
    sa.Column('total_consume', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounts_user_id'), 'accounts', ['user_id'], unique=False)
    op.create_table('api_keys',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('key_name', sa.String(length=100), nullable=False),
    sa.Column('key_prefix', sa.String(length=20), nullable=False),
    sa.Column('key_hash', sa.String(length=64), nullable=False),
    sa.Column('secret_hash', sa.String(length=128), nullable=True),
    sa.Column('encrypted_key', sa.Text(), nullable=True),
    sa.Column('auth_type', sa.String(length=20), nullable=True),
    sa.Column('allowed_ips', sa.ARRAY(sa.String()), nullable=True),
    sa.Column('allowed_repos', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('denied_repos', sa.ARRAY(sa.UUID()), nullable=True),
    sa.Column('rate_limit_rpm', sa.Integer(), nullable=True),
    sa.Column('rate_limit_rph', sa.Integer(), nullable=True),
    sa.Column('daily_quota', sa.BigInteger(), nullable=True),
    sa.Column('monthly_quota', sa.BigInteger(), nullable=True),
    sa.Column('is_balance_enabled', sa.Boolean(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_calls', sa.BigInteger(), nullable=True),
    sa.Column('last_call_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('disabled_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key_hash')
    )
    op.create_index(op.f('ix_api_keys_key_prefix'), 'api_keys', ['key_prefix'], unique=False)
    op.create_index(op.f('ix_api_keys_user_id'), 'api_keys', ['user_id'], unique=False)
    op.create_table('bills',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('bill_no', sa.String(length=50), nullable=False),
    sa.Column('bill_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.String(length=20), nullable=False),
    sa.Column('balance_before', sa.String(length=20), nullable=False),
    sa.Column('balance_after', sa.String(length=20), nullable=False),
    sa.Column('source_type', sa.String(length=20), nullable=True),
    sa.Column('source_id', sa.String(length=50), nullable=True),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_channel', sa.String(length=50), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('bill_no')
    )
    op.create_index(op.f('ix_bills_created_at'), 'bills', ['created_at'], unique=False)
    op.create_index(op.f('ix_bills_environment'), 'bills', ['environment'], unique=False)
    op.create_index(op.f('ix_bills_user_id'), 'bills', ['user_id'], unique=False)
    op.create_table('monthly_bills',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('year', sa.BigInteger(), nullable=False),
    sa.Column('month', sa.BigInteger(), nullable=False),
    sa.Column('environment', sa.String(length=20), nullable=True),
    sa.Column('total_recharge', sa.String(length=20), nullable=True),
    sa.Column('total_consumption', sa.String(length=20), nullable=True),
    sa.Column('net_change', sa.String(length=20), nullable=True),
    sa.Column('beginning_balance', sa.String(length=20), nullable=True),
    sa.Column('ending_balance', sa.String(length=20), nullable=True),
    sa.Column('total_calls', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('details', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('review_comment', sa.Text(), nullable=True),
    sa.Column('generated_by', sa.UUID(), nullable=True),
    sa.Column('generated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('published_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_monthly_bills_environment'), 'monthly_bills', ['environment'], unique=False)
    op.create_index(op.f('ix_monthly_bills_status'), 'monthly_bills', ['status'], unique=False)
    op.create_index(op.f('ix_monthly_bills_user_id'), 'monthly_bills', ['user_id'], unique=False)
    op.create_table('payments',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('payment_no', sa.String(length=50), nullable=False),
    sa.Column('order_no', sa.String(length=50), nullable=False),
    sa.Column('payment_type', sa.String(length=20), nullable=False),
    sa.Column('amount', sa.String(length=20), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('package_id', sa.UUID(), nullable=True),
    sa.Column('package_name', sa.String(length=100), nullable=True),
    sa.Column('payment_method', sa.String(length=20), nullable=True),
    sa.Column('payment_channel', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('transaction_id', sa.String(length=100), nullable=True),
    sa.Column('payer_info', sa.Text(), nullable=True),
    sa.Column('pay_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('callback_url', sa.String(length=500), nullable=True),
    sa.Column('callback_status', sa.String(length=20), nullable=True),
    sa.Column('callback_response', sa.Text(), nullable=True),
    sa.Column('callback_times', sa.BigInteger(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('remark', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('order_no'),
    sa.UniqueConstraint('payment_no')
    )
    op.create_index(op.f('ix_payments_created_at'), 'payments', ['created_at'], unique=False)
    op.create_index(op.f('ix_payments_status'), 'payments', ['status'], unique=False)
    op.create_index(op.f('ix_payments_user_id'), 'payments', ['user_id'], unique=False)
    op.create_table('repositories',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('owner_type', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('slug', sa.String(length=100), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.Text(), nullable=True),
    sa.Column('repo_type', sa.String(length=50), nullable=False),
    sa.Column('protocol', sa.String(length=20), nullable=False),
    sa.Column('adapter_id', sa.String(length=50), nullable=True),
    sa.Column('endpoint_url', sa.String(length=500), nullable=True),
    sa.Column('health_check_url', sa.String(length=500), nullable=True),
    sa.Column('api_docs_url', sa.String(length=500), nullable=True),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.Column('sla_uptime', sa.String(length=10), nullable=True),
    sa.Column('sla_latency_p99', sa.Integer(), nullable=True),
    sa.Column('total_calls', sa.BigInteger(), nullable=True),
    sa.Column('active_keys', sa.Integer(), nullable=True),
    sa.Column('avg_latency_ms', sa.Integer(), nullable=True),
    sa.Column('success_rate', sa.String(length=10), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_by', sa.UUID(), nullable=True),
    sa.Column('reviewed_by', sa.UUID(), nullable=True),
    sa.Column('online_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('offline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repositories_owner_id'), 'repositories', ['owner_id'], unique=False)
    op.create_index(op.f('ix_repositories_repo_type'), 'repositories', ['repo_type'], unique=False)
    op.create_index(op.f('ix_repositories_slug'), 'repositories', ['slug'], unique=False)
    op.create_index(op.f('ix_repositories_status'), 'repositories', ['status'], unique=False)
    op.create_table('api_call_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('api_key_id', sa.UUID(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('request_path', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_params', sa.Text(), nullable=True),
    sa.Column('tester', sa.String(length=100), nullable=True),
    sa.Column('status_code', sa.BigInteger(), nullable=True),
    sa.Column('response_time', sa.String(length=20), nullable=True),
    sa.Column('tokens_used', sa.BigInteger(), nullable=True),
    sa.Column('cost', sa.String(length=20), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['api_key_id'], ['api_keys.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_api_call_logs_api_key_id'), 'api_call_logs', ['api_key_id'], unique=False)
    op.create_index(op.f('ix_api_call_logs_created_at'), 'api_call_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_api_call_logs_repo_id'), 'api_call_logs', ['repo_id'], unique=False)
    op.create_index(op.f('ix_api_call_logs_request_id'), 'api_call_logs', ['request_id'], unique=False)
    op.create_index(op.f('ix_api_call_logs_user_id'), 'api_call_logs', ['user_id'], unique=False)
    op.create_table('key_usage_logs',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('key_id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True),
    sa.Column('endpoint', sa.String(length=255), nullable=True),
    sa.Column('method', sa.String(length=10), nullable=True),
    sa.Column('status_code', sa.Integer(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('tokens_used', sa.Integer(), nullable=True),
    sa.Column('cost', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=50), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['key_id'], ['api_keys.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_key_usage_logs_created_at'), 'key_usage_logs', ['created_at'], unique=False)
    op.create_table('payment_callbacks',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('payment_id', sa.UUID(), nullable=False),
    sa.Column('callback_no', sa.String(length=50), nullable=False),
    sa.Column('channel', sa.String(length=20), nullable=False),
    sa.Column('request_body', sa.Text(), nullable=True),
    sa.Column('request_headers', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=True),
    sa.Column('response_status', sa.BigInteger(), nullable=True),
    sa.Column('parse_result', sa.Text(), nullable=True),
    sa.Column('verify_result', sa.Text(), nullable=True),
    sa.Column('handle_result', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.BigInteger(), nullable=True),
    sa.Column('max_retries', sa.BigInteger(), nullable=True),
    sa.Column('next_retry_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('callback_no')
    )
    op.create_index(op.f('ix_payment_callbacks_created_at'), 'payment_callbacks', ['created_at'], unique=False)
    op.create_index(op.f('ix_payment_callbacks_payment_id'), 'payment_callbacks', ['payment_id'], unique=False)
    op.create_table('pricing_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=True, comment='关联的仓库ID，NULL表示全局默认配置'),
    sa.Column('pricing_type', sa.String(length=20), nullable=False),
    sa.Column('price_per_call', sa.Numeric(precision=10, scale=4), nullable=True, comment='每次调用价格'),
    sa.Column('free_calls', sa.Integer(), nullable=True, comment='免费调用次数'),
    sa.Column('price_per_1k_input_tokens', sa.Numeric(precision=10, scale=4), nullable=True, comment='每1K输入Token价格'),
    sa.Column('price_per_1k_output_tokens', sa.Numeric(precision=10, scale=4), nullable=True, comment='每1K输出Token价格'),
    sa.Column('free_input_tokens', sa.Integer(), nullable=True, comment='免费输入Token数'),
    sa.Column('free_output_tokens', sa.Integer(), nullable=True, comment='免费输出Token数'),
    sa.Column('packages', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='套餐包定义'),
    sa.Column('default_package_id', sa.String(length=50), nullable=True, comment='默认选中的套餐包ID'),
    sa.Column('pricing_tiers', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='阶梯定价配置'),
    sa.Column('vip_discounts', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='VIP等级折扣配置'),
    sa.Column('priority', sa.Integer(), nullable=True, comment='配置优先级，数字越小优先级越高'),
    sa.Column('valid_from', sa.DateTime(timezone=True), nullable=True, comment='配置生效开始时间'),
    sa.Column('valid_until', sa.DateTime(timezone=True), nullable=True, comment='配置生效结束时间'),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('description', sa.Text(), nullable=True, comment='配置说明'),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.UUID(), nullable=True, comment='创建人'),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_pricing_configs_pricing_type'), 'pricing_configs', ['pricing_type'], unique=False)
    op.create_index(op.f('ix_pricing_configs_repo_id'), 'pricing_configs', ['repo_id'], unique=False)
    op.create_index(op.f('ix_pricing_configs_status'), 'pricing_configs', ['status'], unique=False)
    op.create_table('repo_configs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('config_type', sa.String(length=50), nullable=False),
    sa.Column('config_key', sa.String(length=100), nullable=False),
    sa.Column('config_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('config_order', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_configs_config_type'), 'repo_configs', ['config_type'], unique=False)
    op.create_index(op.f('ix_repo_configs_repo_id'), 'repo_configs', ['repo_id'], unique=False)
    op.create_table('repo_endpoints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('path', sa.String(length=200), nullable=False),
    sa.Column('method', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('request_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('response_schema', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('example_request', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('example_response', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('rpm_limit', sa.Integer(), nullable=True),
    sa.Column('rph_limit', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('is_deprecated', sa.Boolean(), nullable=True),
    sa.Column('display_order', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_repo_endpoints_repo_id'), 'repo_endpoints', ['repo_id'], unique=False)
    op.create_table('repo_limits',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('rpm', sa.Integer(), nullable=True),
    sa.Column('rph', sa.Integer(), nullable=True),
    sa.Column('rpd', sa.Integer(), nullable=True),
    sa.Column('burst_limit', sa.Integer(), nullable=True),
    sa.Column('concurrent_limit', sa.Integer(), nullable=True),
    sa.Column('daily_quota', sa.Integer(), nullable=True),
    sa.Column('monthly_quota', sa.Integer(), nullable=True),
    sa.Column('request_timeout', sa.Integer(), nullable=True),
    sa.Column('connect_timeout', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id')
    )
    op.create_table('repo_pricing',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('pricing_type', sa.String(length=20), nullable=False),
    sa.Column('price_per_call', sa.String(length=20), nullable=True),
    sa.Column('price_per_token', sa.String(length=20), nullable=True),
    sa.Column('price_per_mb', sa.String(length=20), nullable=True),
    sa.Column('monthly_price', sa.String(length=20), nullable=True),
    sa.Column('yearly_price', sa.String(length=20), nullable=True),
    sa.Column('free_calls', sa.Integer(), nullable=True),
    sa.Column('free_tokens', sa.Integer(), nullable=True),
    sa.Column('free_quota_days', sa.Integer(), nullable=True),
    sa.Column('packages', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('repo_id')
    )
    op.create_table('repo_stats',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('repo_id', sa.UUID(), nullable=False),
    sa.Column('stat_hour', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_calls', sa.BigInteger(), nullable=True),
    sa.Column('success_calls', sa.BigInteger(), nullable=True),
    sa.Column('failed_calls', sa.BigInteger(), nullable=True),
    sa.Column('avg_latency_ms', sa.String(length=20), nullable=True),
    sa.Column('p50_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p90_latency_ms', sa.Integer(), nullable=True),
    sa.Column('p99_latency_ms', sa.Integer(), nullable=True),
    sa.Column('max_latency_ms', sa.Integer(), nullable=True),
    sa.Column('total_bytes', sa.BigInteger(), nullable=True),
    sa.Column('total_tokens', sa.BigInteger(), nullable=True),
    sa.Column('total_cost', sa.String(length=20), nullable=True),
    sa.Column('unique_keys', sa.Integer(), nullable=True),
    sa.Column('unique_users', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['repo_id'], ['repositories.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('repo_stats')
    op.drop_table('repo_pricing')
    op.drop_table('repo_limits')
    op.drop_index(op.f('ix_repo_endpoints_repo_id'), table_name='repo_endpoints')
    op.drop_table('repo_endpoints')
    op.drop_index(op.f('ix_repo_configs_repo_id'), table_name='repo_configs')
    op.drop_index(op.f('ix_repo_configs_config_type'), table_name='repo_configs')
    op.drop_table('repo_configs')
    op.drop_index(op.f('ix_pricing_configs_status'), table_name='pricing_configs')
    op.drop_index(op.f('ix_pricing_configs_repo_id'), table_name='pricing_configs')
    op.drop_index(op.f('ix_pricing_configs_pricing_type'), table_name='pricing_configs')
    op.drop_table('pricing_configs')
    op.drop_index(op.f('ix_payment_callbacks_payment_id'), table_name='payment_callbacks')
    op.drop_index(op.f('ix_payment_callbacks_created_at'), table_name='payment_callbacks')
    op.drop_table('payment_callbacks')
    op.drop_index(op.f('ix_key_usage_logs_created_at'), table_name='key_usage_logs')
    op.drop_table('key_usage_logs')
    op.drop_index(op.f('ix_api_call_logs_user_id'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_request_id'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_repo_id'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_created_at'), table_name='api_call_logs')
    op.drop_index(op.f('ix_api_call_logs_api_key_id'), table_name='api_call_logs')
    op.drop_table('api_call_logs')
    op.drop_index(op.f('ix_repositories_status'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_slug'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_repo_type'), table_name='repositories')
    op.drop_index(op.f('ix_repositories_owner_id'), table_name='repositories')
    op.drop_table('repositories')
    op.drop_index(op.f('ix_payments_user_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_status'), table_name='payments')
    op.drop_index(op.f('ix_payments_created_at'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_monthly_bills_user_id'), table_name='monthly_bills')
    op.drop_index(op.f('ix_monthly_bills_status'), table_name='monthly_bills')
    op.drop_index(op.f('ix_monthly_bills_environment'), table_name='monthly_bills')
    op.drop_table('monthly_bills')
    op.drop_index(op.f('ix_bills_user_id'), table_name='bills')
    op.drop_index(op.f('ix_bills_environment'), table_name='bills')
    op.drop_index(op.f('ix_bills_created_at'), table_name='bills')
    op.drop_table('bills')
    op.drop_index(op.f('ix_api_keys_user_id'), table_name='api_keys')
    op.drop_index(op.f('ix_api_keys_key_prefix'), table_name='api_keys')
    op.drop_table('api_keys')
    op.drop_index(op.f('ix_accounts_user_id'), table_name='accounts')
    op.drop_table('accounts')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_user_profiles_user_id'), table_name='user_profiles')
    op.drop_table('user_profiles')
    op.drop_index(op.f('ix_user_operation_logs_username'), table_name='user_operation_logs')
    op.drop_index(op.f('ix_user_operation_logs_user_id'), table_name='user_operation_logs')
    op.drop_index(op.f('ix_user_operation_logs_session_id'), table_name='user_operation_logs')
    op.drop_index(op.f('ix_user_operation_logs_email'), table_name='user_operation_logs')
    op.drop_index(op.f('ix_user_operation_logs_created_at'), table_name='user_operation_logs')
    op.drop_index(op.f('ix_user_operation_logs_category'), table_name='user_operation_logs')
    op.drop_index(op.f('ix_user_operation_logs_action'), table_name='user_operation_logs')
    op.drop_index('idx_user_op_user_time', table_name='user_operation_logs')
    op.drop_index('idx_user_op_session_time', table_name='user_operation_logs')
    op.drop_index('idx_user_op_category_time', table_name='user_operation_logs')
    op.drop_index('idx_user_op_action_time', table_name='user_operation_logs')
    op.drop_table('user_operation_logs')
    op.drop_index(op.f('ix_system_configs_key'), table_name='system_configs')
    op.drop_index(op.f('ix_system_configs_category'), table_name='system_configs')
    op.drop_table('system_configs')
    op.drop_index(op.f('ix_roles_name'), table_name='roles')
    op.drop_table('roles')
    op.drop_index(op.f('ix_reconciliation_records_reconcile_date'), table_name='reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_records_channel'), table_name='reconciliation_records')
    op.drop_table('reconciliation_records')
    op.drop_index(op.f('ix_reconciliation_disputes_reconciliation_id'), table_name='reconciliation_disputes')
    op.drop_table('reconciliation_disputes')
    op.drop_table('recharge_packages')
    op.drop_index(op.f('ix_quotas_user_id'), table_name='quotas')
    op.drop_table('quotas')
    op.drop_index(op.f('ix_platform_accounts_channel'), table_name='platform_accounts')
    op.drop_table('platform_accounts')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    op.drop_index(op.f('ix_audit_logs_username'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_index('idx_audit_user_time', table_name='audit_logs')
    op.drop_index('idx_audit_resource_time', table_name='audit_logs')
    op.drop_index('idx_audit_action_time', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_adapters_status'), table_name='adapters')
    op.drop_index(op.f('ix_adapters_adapter_type'), table_name='adapters')
    op.drop_table('adapters')
    op.drop_index(op.f('ix_adapter_instances_repo_id'), table_name='adapter_instances')
    op.drop_table('adapter_instances')
    # ### end Alembic commands ###
